### ISSUE TITLE
Cards of Wild Nullreference Exception

### ISSUE THREAD

**Issue by jensvdh** [worldofbalance/wob-server#6] opened 2016-03-29 21:50 UTC
Hey guys,

Whenever I run the latest development branch the Cards Of Wild server immediately crashes and throws a nullreference exception.

![minigameservers_java_-__wob-server__-_wob-server_-____projects_831_wob-server_](https://cloud.githubusercontent.com/assets/2640481/14124962/83a320a0-f5bd-11e5-833d-eb47657dca6e.png)

Thoughts?

**Comment by jensvdh** [comment] 2016-03-29 21:50
@worldofbalance/cards-of-wild

**Comment by haichuand** [comment] 2016-03-29 23:55
I don't have this error, but I get another exception:

[Running Rhino] Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/pool/ObjectPool
[Running Rhino] 	at dataAccessLayer.GameDB.<init>(GameDB.java:33)
[Running Rhino] 	at dataAccessLayer.DAO.<init>(DAO.java:22)
[Running Rhino] 	at dataAccessLayer.DAO.getInstance(DAO.java:33)
[Running Rhino] 	at core.GameServer.<init>(GameServer.java:74)
[Running Rhino] 	at core.GameServer.main(GameServer.java:366)
[Running Rhino] Caused by: java.lang.ClassNotFoundException: org.apache.commons.pool.ObjectPool
[Running Rhino] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[Running Rhino] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)

**Comment by jensvdh** [comment] 2016-03-29 23:56
@haichuand you're referring to #3

**Comment by haichuand** [comment] 2016-03-30 00:04
I see. How did you get COW server started? I couldn't get past the Running Rhino server error

**Comment by niculistana** [comment] 2016-03-30 00:49
@haichuand, let's move this discussion to #3.

**Comment by haichuand** [comment] 2016-03-30 02:33
I was able to start the COW server and found the NPE issue. The problem was caused by repeat thread start code in MiniGame.java, line 92~101. After deleting the extra code (and the unnecessary brackets) the NPE was solved. And the Running Rhino issue was solved too!

**Comment by niculistana** [comment] 2016-03-30 03:20
@haichuand, is it running both the .jar files?

**Comment by haichuand** [comment] 2016-03-30 03:45
Yes it's running both RR and COW mini game jar files.

**Comment by rujoota** [comment] 2016-03-30 07:12
It wont be the bug anymore as code for cards of wild is merged and its no more pointing to any jar. I will merge the code in main development branch soon.

**Closed as completed by rujoota** 2016-03-30 07:12 UTC
Labels: bug

**Comment by jensvdh** [comment] 2016-03-30 16:31
Thanks!
